### ISSUE TITLE
Nuxt 3.12.3 composable types break when @vite-pwa/nuxt is installed

### ISSUE THREAD

**Issue by Bombastickj** [vite-pwa/nuxt#146] opened 2024-07-02 22:28 UTC
Hello,
I've found an issue with this module since upgrading to Nuxt 3.12.3. (Nuxt 3.12.2 worked completely fine)

It seems like the types of a custom plugin, getting passed through a composable, are not correctly exposed.
After lots of debugging and trying to find the error, I was able to create a minimal reproduction:

https://stackblitz.com/edit/github-j6cwz8?file=nuxt.config.ts

To see the error disappear, uninstall @vite-pwa/nuxt
I am also not quite sure if this is a bug from this module or mabe nuxt itself

I hope this helps!

**Comment by DrFuehrer02** [comment] 2024-07-03 09:11
I ran into the same issue this morning.

**Comment by userquin** [comment] 2024-07-03 14:28
I'm working to fix this, in your SB reproduction, you can add `.mjs` extension to `pwa-icons` plugin entry (`.nuxt/types/plugins.d.ts`) and should work (I'm checking waht's happening since you're using latest nuxt and latest ts):

![imagen](https://github.com/vite-pwa/nuxt/assets/6311119/ac304ccd-1ca4-4f66-980c-3fec6b9dde20)

**Comment by userquin** [comment] 2024-07-03 17:17
@Bombastickj do you have a reproduction for Nuxt 3.12.2 ?

**Comment by Bombastickj** [comment] 2024-07-03 17:47
Yes of course! Here's the same reproduction working with Nuxt 3.12.2.
(I also had to downgrade to vue-tsc 1.8.27)

https://stackblitz.com/edit/github-1nrcnd?file=nuxt.config.ts

**Comment by Bombastickj** [comment] 2024-07-03 18:50
Sorry @userquin! 
I also had to downgrade to typescript 5.4.5. The reproduction should be updated and working now.

**Comment by userquin** [comment] 2024-07-03 19:50
@Bombastickj thx, it works

I'm going to release a new minor with the fix.

**Comment by userquin** [comment] 2024-07-03 20:10
@Bombastickj should be fixed in `v0.9.0`

**Comment by Bombastickj** [comment] 2024-07-03 20:13
That sounds great, thank you! @userquin

**Comment by userquin** [comment] 2024-07-04 14:37
package manager?

**Comment by vasilistotskas** [comment] 2024-07-04 14:38
package manager pnpm version 9.4.0

**Comment by userquin** [comment] 2024-07-04 14:42
@vasilistotskas do you have `shamelly-hoisted=true`  in `.npmrc` (you can try adding `typescript.hoisted: ['vite-plugin-pwa']` and run `pnpm install`)

**Comment by vasilistotskas** [comment] 2024-07-04 16:02
```
//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}
@vasilistotskas:registry=https://npm.pkg.github.com
always-auth=true
auto-install-peers=true
shamefully-hoist=true
strict-peer-dependencie=false
shared-workspace-lockfile=false
package-import-method=clone-or-copy

```

Thats the content of my `.npmrc` file

**Comment by dargmuesli** [comment] 2024-07-04 22:33
> Im getting type errors with `"nuxt": "3.12.3"` ,`"@vite-pwa/nuxt": "0.9.0"` and `"typescript": "5.5.3"`

Same for me on `"typescript": "5.4.5"`, so typescript does not seem to be the culprit. Most likely it's not possible to import from something `virtual:...` in the `.nuxt` directory outside runtime?

**Comment by danielroe** [comment] 2024-07-05 08:21
Yes, TypeScript doesn't know the types for any virtual import unless you provide a declaration file to tell it about those types. (I'm assuming you haven't created one for `virtual:pwa-assets/icons`?) If you have created a declaration file you also may need to ensure TS can resolve it with `compilerOptions.paths`

**Comment by userquin** [comment] 2024-07-05 09:11
Daniel, the virtual module is declared in pwa-assets.d.ts in pwa plugin here https://github.com/vite-pwa/vite-plugin-pwa/blob/main/pwa-assets.d.ts#L26, I add the types in prepare types hook here https://github.com/vite-pwa/nuxt/blob/main/src/utils/module.ts#L98

**Closed** 2024-07-06 13:56 UTC

**Comment by userquin** [comment] 2024-07-06 13:59
@vasilistotskas can you try with `v0.9.1`? The plugin icons now should be ok without pwa assets installed.

**Comment by vasilistotskas** [comment] 2024-07-06 15:24
Yes the errors gone 💯
